### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data type between the list_ and array_list variables in your provided code. The list_ variable is a Python list containing strings, while the array_list variable is a NumPy array created from the list_ variable. The NumPy array will have a different data type compared to the Python list

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Type of list_:", type(list_))
print("Type of array_list:", type(array_list))


Type of list_: <class 'list'>
Type of array_list: <class 'numpy.ndarray'>


In this code snippet, the type() function is used to print the data types of both list_ and array_list. list_ is of type list, and array_list is of type numpy.ndarray. The numpy.ndarray type represents a NumPy array.

### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [6]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
### array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.
### Consider the below code to answer further questions:
### import numpy as np
### num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
### num_array = np.array(object = num_list)

In [7]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


### Q4. Write a code to find the following characteristics of variable, num_array: (i) shape (ii) size

In [9]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Print the shape of num_array
print("Shape of num_array:", num_array.shape)

# (ii) Print the size of num_array
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy arraycreation function. [Hint: The size of the array will be 9 and the shape will be (3,3).]


In [11]:
import numpy as np

# Create a 3x3 matrix with zeros
zeros_matrix = np.zeros((3, 3))

print("3x3 Matrix with Zeros:")
print(zeros_matrix)


3x3 Matrix with Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q6. Create an identity matrix of shape (5,5) using numpy functions? [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [12]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
